/** Utilities to import external sources: web URLs and YouTube transcripts */

/**
 * Fetch and extract readable text from a web URL.
 * Uses a CORS-friendly approach via the Gemini document understanding endpoint
 * (falls back to fetch + simple HTML stripping if the model is unavailable).
 */
export async function fetchUrlText(url: string): Promise<string> {
  // Simple approach: fetch via allorigins CORS proxy and strip HTML tags
  const proxyUrl = `https://api.allorigins.win/get?url=${encodeURIComponent(url)}`;
  const resp = await fetch(proxyUrl);
  if (!resp.ok) throw new Error(`Failed to fetch URL (status ${resp.status})`);
  const data = await resp.json();
  const html: string = data.contents || '';

  // Strip tags, decode entities
  const text = html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/\s{3,}/g, '\n\n')
    .trim();

  if (!text || text.length < 50) throw new Error('Could not extract readable content from URL.');
  return text;
}

/** Extract YouTube video ID from any YouTube URL format. */
export function extractYouTubeId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([A-Za-z0-9_-]{11})/,
    /youtube\.com\/shorts\/([A-Za-z0-9_-]{11})/,
  ];
  for (const p of patterns) {
    const m = url.match(p);
    if (m) return m[1];
  }
  return null;
}

/**
 * Fetch the transcript (captions) of a YouTube video.
 * Uses the public timedtext API — works for videos with English captions.
 */
export async function fetchYouTubeTranscript(videoId: string): Promise<{ text: string; isAutoGenerated: boolean }> {
  // Fetch caption track list
  const proxyBase = 'https://api.allorigins.win/get?url=';
  const listUrl = `https://www.youtube.com/watch?v=${videoId}`;
  const pageResp = await fetch(`${proxyBase}${encodeURIComponent(listUrl)}`);
  if (!pageResp.ok) throw new Error('Could not reach YouTube.');
  const pageData = await pageResp.json();
  const html = pageData.contents as string;

  // Extract caption track URL from page HTML
  const captionMatch = html.match(/"captionTracks":\s*\[.*?"baseUrl":"([^"]+)"/);
  if (!captionMatch) {
    throw new Error('No captions found for this video. The video may not have English captions available.');
  }
  
  const captionUrl = captionMatch[1].replace(/\\u0026/g, '&');
  const isAutoGenerated = captionUrl.includes('kind=asr');

  // Fetch caption XML
  const capResp = await fetch(`${proxyBase}${encodeURIComponent(captionUrl)}`);
  if (!capResp.ok) throw new Error('Failed to download captions.');
  const capData = await capResp.json();
  const xml = capData.contents as string;

  // Parse <text> elements from XML
  const texts: string[] = [];
  const textMatches = xml.matchAll(/<text[^>]*>([^<]*)<\/text>/g);
  for (const m of textMatches) {
    const decoded = m[1]
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .trim();
    if (decoded) texts.push(decoded);
  }

  if (texts.length === 0) throw new Error('Caption file was empty.');
  return { text: texts.join(' '), isAutoGenerated };
}
